---
# Install rails app guestbook
- hosts: redis
  remote_user: root
  become: yes

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: redis
      redis_bind_interface: 0.0.0.0   # Set the interface to 0.0.0.0 to listen on all interfaces.
